### ISSUE TITLE
read buff is too small

### ISSUE THREAD

**Issue by c-zhenyu** [Ali-aqrabawi/gomiko#14]
func (c *SSHConn) Read() (string, error) {

	buff := make([]byte, 2048) // need 204800 or bigger

	n, err := c.reader.Read(buff)
	return string(buff[:n]), err

}

**Comment by Ali-aqrabawi** [comment]
Can you give more details

**Comment by c-zhenyu** [comment]
Hi,
您好，我是一个Golang初学者（英文也不好），我来描述一下我遇到的问题吧：
比如在执行“show run”的时候，在返回的信息中，只能输出一部分，比如这个48口交换机只输出到了24口的配置信息，如下图：


Hello, I am a Golang beginner (not good in English), let me describe the problem I encountered:
For example, when executing "show run", only part of the returned information can be output. For example, this 48-port switch only outputs the configuration information of 24 ports, as shown in the following figure:




On 03/19/2021 ***@***.***> wrote：

Can you give more details

**Comment by c-zhenyu** [comment]
![image](https://user-images.githubusercontent.com/45548599/111740873-743a2c80-88c0-11eb-9537-cc3df9fd0315.png)
