### ISSUE TITLE
I unable to use the gomiko.SecretOption

### ISSUE THREAD

**Issue by salonijain18** [Ali-aqrabawi/gomiko#15]
The error I get  is "SecretOption not declared by package gomikocompiler[UndeclaredImportedName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)"

**Comment by salonijain18** [comment]
The issue got resolved for me by taking the latest pull with the master tag as mentioned below 
go get -u github.com/Ali-aqrabawi/gomiko/pkg@master

**Comment by Ali-aqrabawi** [comment]
it was a release related issue.
published v0.0.2 release.
