### ISSUE TITLE
Get Config without enable password is failing

### ISSUE THREAD

**Issue by salonijain18** [Ali-aqrabawi/gomiko#16]
To resolve the issue of SecretOption I took the latest pull of the library with the master tag as shown below
**go get -u github.com/Ali-aqrabawi/gomiko/pkg@master**
and now even for command which doesn't required a enable password it is asking for it and giving me the below error
**failed to send enable password, make sure you have passed SecretOption() option: timeout while reading, read pattern not found pattern**

**Comment by no-such-anthony** [comment]
Hi Saloni - When you enable from the CLI does it change the base prompt at all? In this example, the base prompt would be considered R2.

R2>en
Password:
R2#

Anthony

**Comment by Ali-aqrabawi** [comment]
are you sure the device does not require enable password ? this error happen when the device prompting to enable password.
can you share more details? what command you are executing? the code block?
