### ISSUE TITLE
Add setting for custom timeouts?

### ISSUE THREAD

**Issue by jthampton** [Ali-aqrabawi/gomiko#20]
Can you add a parameter or setting to allow for custom timeouts?  I see the default for a connection is set to 6 seconds.  Sometimes I timeout when connecting to a device and sometimes it works perfectly.  I would like to adjust the timeout to see if bumping to 10 seconds would allow a connection to be established more consistently.  I'm currently working with both Cisco ASA and Nexus devices, and I see that both devices have this behavior.

Let me know how to contribute and maybe I can work on a potential fix.  (And great work on this library - It's proven to be very helpful!)

**Comment by Ali-aqrabawi** [comment]
No specific fancy guidelines for contributing. If you would like to fix this please do.
Keep in mind the following:
1) add unittest. And make sure all tests pass.
2) update the readme.
And submit PR.
Thanks.
